### ISSUE TITLE
Delete exam

### ISSUE THREAD

**Issue by melaniemai** [rymandn/SeniorCapstoneProject-CS5001#4]
- [x] Add trash icon to table row
- [ ] When user clicks on trash icon:
  - [ ] A modal/dialog should appear asking if they're sure they want to delete the exam
  - [ ] If click "Delete" exam is removed

**Comment by conleyrj** [comment]
Started implementation of this feature as part of [this pull request](https://github.com/rymandn/SeniorCapstoneProject-CS5001/pull/2). Wasn't sure on specific trash icon to use so did generic delete button for now. Also held off on creating confirmation dialog to make it easier for testing and other implementation for now.

**Comment by melaniemai** [comment]
#13
